
CREATE TABLE ADDRESS
(
  ADDRESS      VARCHAR(500) NOT NULL COMMENT '주소명',
  ADDRESS_CODE VARCHAR(50)  NOT NULL COMMENT '주소코드',
  PRIMARY KEY (ADDRESS_CODE)
) COMMENT '주소코드';

CREATE TABLE GENDER
(
  GENDER_CODE VARCHAR(50)  NOT NULL COMMENT '성별ID',
  GENDER      VARCHAR(500) NOT NULL COMMENT '성별',
  PRIMARY KEY (GENDER_CODE)
) COMMENT '성별';

CREATE TABLE HOBBY_CODE
(
  HOBBY_NAME_ID VARCHAR(500) NOT NULL COMMENT '취미코드ID',
  UNIQUE_ID     VARCHAR(500) NOT NULL COMMENT '유니크_ID'
) COMMENT '취미코드';

CREATE TABLE MEMBERS_HOBBY
(
  HOBBY_NAME    VARCHAR(500) NOT NULL COMMENT '취미명',
  HOBBY_NAME_ID VARCHAR(500) NOT NULL COMMENT '취미코드ID',
  PRIMARY KEY (HOBBY_NAME_ID)
) COMMENT '회원_취미';

CREATE TABLE MEMBERS_INFO
(
  NAME         VARCHAR(500) NOT NULL COMMENT '이름',
  AGE          INTEGER      NOT NULL COMMENT '나이',
  PHONENUMBER  VARCHAR(500) NOT NULL COMMENT '전화번호',
  UNIQUE_ID    VARCHAR(500) NOT NULL COMMENT '유니크_ID',
  GENDER_CODE  VARCHAR(50)  NOT NULL COMMENT '성별ID',
  ADDRESS_CODE VARCHAR(50)  NOT NULL COMMENT '주소코드',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '회원정보';

CREATE TABLE MEMBERS_LOGIN
(
  UNIQUE_ID        VARCHAR(500) NOT NULL COMMENT '유니크_ID',
  E_MAIL           VARCHAR(500) NOT NULL COMMENT '이메일',
  MEMBERS_LOGIN_ID VARCHAR(500) NOT NULL COMMENT '회원정보_로그인_ID',
  PRIMARY KEY (MEMBERS_LOGIN_ID)
) COMMENT '회원정보_로그인';

ALTER TABLE MEMBERS_LOGIN
  ADD CONSTRAINT FK_MEMBERS_INFO_TO_MEMBERS_LOGIN
    FOREIGN KEY (UNIQUE_ID)
    REFERENCES MEMBERS_INFO (UNIQUE_ID);

ALTER TABLE HOBBY_CODE
  ADD CONSTRAINT FK_MEMBERS_HOBBY_TO_HOBBY_CODE
    FOREIGN KEY (HOBBY_NAME_ID)
    REFERENCES MEMBERS_HOBBY (HOBBY_NAME_ID);

ALTER TABLE HOBBY_CODE
  ADD CONSTRAINT FK_MEMBERS_INFO_TO_HOBBY_CODE
    FOREIGN KEY (UNIQUE_ID)
    REFERENCES MEMBERS_INFO (UNIQUE_ID);

ALTER TABLE MEMBERS_INFO
  ADD CONSTRAINT FK_GENDER_TO_MEMBERS_INFO
    FOREIGN KEY (GENDER_CODE)
    REFERENCES GENDER (GENDER_CODE);

ALTER TABLE MEMBERS_INFO
  ADD CONSTRAINT FK_ADDRESS_TO_MEMBERS_INFO
    FOREIGN KEY (ADDRESS_CODE)
    REFERENCES ADDRESS (ADDRESS_CODE);
