-- SELECT 
-- FROM T1
-- INNER JOIN T2 
-- ON CONDITION

SELECT COUNT(*), T_MEMS.AGE 
FROM members AS T_MEMS
	INNER JOIN members_login AS T_MEMS_LOGIN
	ON T_MEMS.MEMBERS_ID = T_MEMS_LOGIN.MEMBERS_ID
GROUP BY T_MEMS.AGE;