SELECT T_FAC.COMPANY, T_CAR_INFO.CAR_NAME, COUNT(*) AS CNT
FROM (factorys AS T_FAC 
INNER JOIN car_infors AS T_CAR_INFO
ON T_FAC.COMPANY_ID = T_CAR_INFO.COMPANY_ID)
INNER JOIN `options` AS T_OPTS
ON T_CAR_INFO.CAR_INFOR_ID = T_OPTS.CAR_INFOR_ID
group by T_FAC.COMPANY_ID, T_CAR_INFO.CAR_INFOR_ID
;

INSERT INTO `OPTIONS`
(OPTION_ID, CAR_INFOR_ID, OPTION_INFOR_ID)
value
('O006','CI001','OI005'),
('O008', 'CI001', 'OI003'),
('O007', 'CI002', 'OI004')
;
INSERT INTO `OPTIONS`
(OPTION_ID, CAR_INFOR_ID, OPTION_INFOR_ID)
value
('O008', 'CI001', 'OI003'),
('O007', 'CI002', 'OI004')
;
SELECT * FROM OPTIONS ;

delete from `OPTIONS`
where car_infor_id = 'CI001' and option_infor_id = 'OI003'
;
SELECT T_FAC.COMPANY, T_CAR_INFO.CAR_NAME
		, T_CAR_INFO.CAR_INFOR_ID
FROM (factorys AS T_FAC 
INNER JOIN car_infors AS T_CAR_INFO
ON T_FAC.COMPANY_ID = T_CAR_INFO.COMPANY_ID)
;
