
CREATE TABLE BLOOD_P
(
  BLOOD_P    INTEGER NOT NULL COMMENT '혈압',
  BLOOD_P_ID INTEGER NOT NULL COMMENT '혈압ID',
  PRIMARY KEY (BLOOD_P_ID)
) COMMENT '혈압';

CREATE TABLE BLOOD_S
(
  BLOOD_S    INTEGER NOT NULL COMMENT '혈당',
  BLOOD_S_ID INTEGER NOT NULL COMMENT '혈당ID',
  PRIMARY KEY (BLOOD_S_ID)
) COMMENT '혈당';

CREATE TABLE GENDER
(
  GENDER    VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_ID VARCHAR(50) NOT NULL COMMENT '성별ID',
  PRIMARY KEY (GENDER_ID)
) COMMENT '성별';

CREATE TABLE IMPROVMENT
(
  IMPROVMENT    VARCHAR(500) NOT NULL COMMENT '유지방안',
  IMPROVMENT_ID VARCHAR(500) NOT NULL COMMENT '유지방안ID',
  PRIMARY KEY (IMPROVMENT_ID)
) COMMENT '유지방안';

CREATE TABLE MEDICALCHECKUP
(
  MEDICALCHECKUP    VARCHAR(500) NOT NULL COMMENT '검진',
  MEDICALCHECKUP_ID VARCHAR(500) NOT NULL COMMENT '검진ID',
  NAME_ID           VARCHAR(500) NOT NULL COMMENT '이름ID',
  GENDER_ID         VARCHAR(50)  NOT NULL COMMENT '성별ID',
  TALL_WEIGHT_ID    VARCHAR(500) NOT NULL COMMENT '키ID',
  BLOOD_P_ID        INTEGER      NOT NULL COMMENT '혈압ID',
  RESULT_ID         VARCHAR(500) NOT NULL COMMENT '검진결과ID',
  WEIGHT_ID         VARCHAR(500) NOT NULL COMMENT '몸무게ID',
  BLOOD_S_ID        INTEGER      NOT NULL COMMENT '혈당ID',
  PRIMARY KEY (MEDICALCHECKUP_ID)
) COMMENT '건강검진';

CREATE TABLE NAME
(
  NAME    VARCHAR(500) NOT NULL COMMENT '이름',
  NAME_ID VARCHAR(500) NOT NULL COMMENT '이름ID',
  PRIMARY KEY (NAME_ID)
) COMMENT '이름';

CREATE TABLE RECHECKUP
(
  RECHECKUP         VARCHAR(500) NOT NULL COMMENT '재검진',
  RECHECKUP_ID      VARCHAR(500) NOT NULL COMMENT '재검진ID',
  RECHECKUP_LIST_ID VARCHAR(500) NOT NULL COMMENT '재검진항목ID',
  PRIMARY KEY (RECHECKUP_ID)
) COMMENT '재검진';

CREATE TABLE RECHECKUP_LIST
(
  RECHECKUP_LIST    VARCHAR(500) NOT NULL COMMENT '재검진항목',
  RECHECKUP_LIST_ID VARCHAR(500) NOT NULL COMMENT '재검진항목ID',
  PRIMARY KEY (RECHECKUP_LIST_ID)
) COMMENT '재검진항목';

CREATE TABLE RESULT
(
  RESULT_VALUE    VARCHAR(500) NOT NULL COMMENT '검진결과',
  RESULT_VALUE_ID VARCHAR(500) NOT NULL COMMENT '검진결과ID',
  RECHECKUP_ID    VARCHAR(500) NOT NULL COMMENT '재검진ID',
  IMPROVMENT_ID   VARCHAR(500) NOT NULL COMMENT '유지방안ID',
  PRIMARY KEY (RESULT_VALUE_ID)
) COMMENT '검진결과';

CREATE TABLE TALL
(
  TALL_WEIGHT    VARCHAR(500) NOT NULL COMMENT '키',
  TALL_WEIGHT_ID VARCHAR(500) NOT NULL COMMENT '키ID',
  PRIMARY KEY (TALL_WEIGHT_ID)
) COMMENT '키';

CREATE TABLE WEIGHT
(
   WEIGHT   VARCHAR(500) NOT NULL COMMENT '몸무게',
  WEIGHT_ID VARCHAR(500) NOT NULL COMMENT '몸무게ID',
  PRIMARY KEY (WEIGHT_ID)
) COMMENT '몸무게';

ALTER TABLE MEDICALCHECKUP
  ADD CONSTRAINT FK_NAME_TO_MEDICALCHECKUP
    FOREIGN KEY (NAME_ID)
    REFERENCES NAME (NAME_ID);

ALTER TABLE MEDICALCHECKUP
  ADD CONSTRAINT FK_GENDER_TO_MEDICALCHECKUP
    FOREIGN KEY (GENDER_ID)
    REFERENCES GENDER (GENDER_ID);

ALTER TABLE MEDICALCHECKUP
  ADD CONSTRAINT FK_TALL_TO_MEDICALCHECKUP
    FOREIGN KEY (TALL_WEIGHT_ID)
    REFERENCES TALL (TALL_WEIGHT_ID);

ALTER TABLE MEDICALCHECKUP
  ADD CONSTRAINT FK_BLOOD_P_TO_MEDICALCHECKUP
    FOREIGN KEY (BLOOD_P_ID)
    REFERENCES BLOOD_P (BLOOD_P_ID);

ALTER TABLE MEDICALCHECKUP
  ADD CONSTRAINT FK_RESULT_TO_MEDICALCHECKUP
    FOREIGN KEY (RESULT_ID)
    REFERENCES RESULT (RESULT_VALUE_ID);

ALTER TABLE MEDICALCHECKUP
  ADD CONSTRAINT FK_WEIGHT_TO_MEDICALCHECKUP
    FOREIGN KEY (WEIGHT_ID)
    REFERENCES WEIGHT (WEIGHT_ID);

ALTER TABLE MEDICALCHECKUP
  ADD CONSTRAINT FK_BLOOD_S_TO_MEDICALCHECKUP
    FOREIGN KEY (BLOOD_S_ID)
    REFERENCES BLOOD_S (BLOOD_S_ID);

ALTER TABLE RECHECKUP
  ADD CONSTRAINT FK_RECHECKUP_LIST_TO_RECHECKUP
    FOREIGN KEY (RECHECKUP_LIST_ID)
    REFERENCES RECHECKUP_LIST (RECHECKUP_LIST_ID);

ALTER TABLE RESULT
  ADD CONSTRAINT FK_RECHECKUP_TO_RESULT
    FOREIGN KEY (RECHECKUP_ID)
    REFERENCES RECHECKUP (RECHECKUP_ID);

ALTER TABLE RESULT
  ADD CONSTRAINT FK_IMPROVMENT_TO_RESULT
    FOREIGN KEY (IMPROVMENT_ID)
    REFERENCES IMPROVMENT (IMPROVMENT_ID);
